#!/bin/bash
# Docker entrypoint: bootstrap config files into the mounted volume, then run hermes.
set -e

HERMES_HOME="/opt/data"
INSTALL_DIR="/opt/hermes"

# Create essential directory structure.  Cache and platform directories
# (cache/images, cache/audio, platforms/whatsapp, etc.) are created on
# demand by the application — don't pre-create them here so new installs
# get the consolidated layout from get_hermes_dir().
mkdir -p "$HERMES_HOME"/{cron,sessions,logs,hooks,memories,skills}

# .env
if [ ! -f "$HERMES_HOME/.env" ]; then
    cp "$INSTALL_DIR/.env.example" "$HERMES_HOME/.env"
fi

# config.yaml
# When ANTHROPIC_API_KEY is set and no config.yaml exists, generate a minimal
# config that points directly at Anthropic instead of copying the example file
# (which defaults to provider: "auto" / base_url: openrouter.ai and causes 404
# errors on Railway when only an Anthropic key is present).
if [ ! -f "$HERMES_HOME/config.yaml" ]; then
    if [ -n "$ANTHROPIC_API_KEY" ]; then
        # Use ANTHROPIC_MODEL env var if set, otherwise fall back to a known-good default.
        _MODEL="${ANTHROPIC_MODEL:-claude-3-5-sonnet-20241022}"
        cat > "$HERMES_HOME/config.yaml" <<EOF
# Auto-generated by docker/entrypoint.sh for Anthropic provider.
# Edit this file to customise model, toolsets, memory, etc.
model:
  provider: "anthropic"
  default: "${_MODEL}"

terminal:
  backend: "local"
  cwd: "."
  timeout: 180
  lifetime_seconds: 300

memory:
  memory_enabled: true
  user_profile_enabled: true

agent:
  max_turns: 60
  verbose: false
EOF
        echo "entrypoint: created config.yaml for Anthropic provider (model: ${_MODEL})"
    else
        cp "$INSTALL_DIR/cli-config.yaml.example" "$HERMES_HOME/config.yaml"
    fi
fi

# SOUL.md
if [ ! -f "$HERMES_HOME/SOUL.md" ]; then
    cp "$INSTALL_DIR/docker/SOUL.md" "$HERMES_HOME/SOUL.md"
fi

# Sync bundled skills (manifest-based so user edits are preserved)
if [ -d "$INSTALL_DIR/skills" ]; then
    python3 "$INSTALL_DIR/tools/skills_sync.py"
fi

exec hermes "$@"
